name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  PROJECT_ID: peerless-sensor-493403-m2
  REGION: us-central1
  SERVICE: smart-mobility
  IMAGE: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure docker for gcr
        run: gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE }}
          region: ${{ env.REGION }}
          allow-unauthenticated: true
